import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import {UserProvider} from "@/lib/app/context/user";
import AppLayout from "@/layouts/AppLayout";
import React from "react";
import {LoadingProvider} from "@/lib/app/context/loading";
import {ToastProvider} from "@/lib/app/context/toast";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html className={"h-full"} lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
        >
        <UserProvider>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <LoadingProvider>
                    <ToastProvider>
                        <AppLayout>
                            {children}
                        </AppLayout>
                    </ToastProvider>
                </LoadingProvider>
            </ThemeProvider>
        </UserProvider>
        </body>
        </html>
    );
}
